kind = "mobile"
previewPath = "/"
title = "WifiPortal"
version = "1.0.0"
id = "artifacts/wifiportal"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/" ]
localPort = 25892

[services.development]
run = "pnpm --filter @workspace/wifiportal run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wifiportal", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/wifiportal", "run", "serve" ]

[services.env]
PORT = "25892"
BASE_PATH = "/"
